### ISSUE TITLE
Develop Homepage with Navigation Bar, Header, and Footer

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#1]
**Description:**
Design the homepage of the application with a navigation bar, header, and footer. The menu should include links to Home, About, Contribute, Contact, and Tools. Ensure that the layout is clean and responsive.

**Acceptance Criteria:**
- Add a header with a logo.
- Create a menu with links to Home, About, Contribute, Contact, and Tools.
- Add a footer.
- Ensure the design is responsive across all devices.
- Follow the layout from the provided image.

![IMG_4013](https://github.com/user-attachments/assets/2e81b5a7-7466-4f16-8144-e9a022f08c88)

**Comment by nikkr008** [comment]
[feature]: started working on issue #1

**Comment by Saichandra2520** [comment]
Can you please assign this to me? @alar12
