### ISSUE TITLE
Add functionality to display most recently used tools at the top of tool list

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#12]
**Description**:
As a user 
I need a "Recently used" label feature 
So that I quickly navigate to the tool I am frequently using.

We need to implement a functionality where, when a tool is clicked or used, it is moved to the top of the tools list. Additionally, the first three most recently used tools should have a "Recently Used" label. This order and the "Recently Used" status should persist even after refreshing the page by storing the data as a JSON object token.

**Acceptance Criteria**:

- [ ] When a tool is clicked or used, it moves to the top of the tools list.
- [ ] The first three tools in the list should display a "Recently Used" label.
- [ ] The tools list should automatically reorder after a tool is used
    - [ ] The most recently used tool appearing first.
- [ ] The state should be stored as a JSON object token. 
- [ ] The recently used tools persist across page refreshes.
- [ ] The order of the tools should remain consistent during 
    - [ ] the session and 
    - [ ] after refreshing the page.
- [ ] The "Recently Used" labels should remain consistent during 
     - [ ] the session and 
     - [ ] after refreshing the page.
- [ ] This feature should be implemented for all tools on the tools page.

![image](https://github.com/user-attachments/assets/1e6e22a7-f008-4232-8b60-d709104f43a5)

**Comment by cubap** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
