### ISSUE TITLE
UI Refinement Tasks

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#13]
**Tasks**:
Menu Toggle Issue:
The menu toggle is not functioning properly; it does not respond on the first click.
It menu should open/close on the first click.

**Menu Option Color**:
The current color of the menu options is not clearly visible against the background.
Update the menu option colors for better visibility.

**Menu Bar Responsiveness**:
When the menu bar is toggled, it covers the content in the Tools section on the homepage.
Make the menu responsive so it does not obstruct homepage content.

**Footer Updates**:
Remove the "Home" section from the footer.
Add icons next to the remaining footer menu options, similar to the footer on rerum.io.

Making these changes improves the UI

**Comment by cubap** [comment]
You all are in control of all the style choices, but it is helpful as a group to agree on a few models that you let inspire you. An app or website that feels right for different UI aspects: color palette, use of space, animations/interactions, design.
