### ISSUE TITLE
Add New Tools (Adno, Universal Viewer) and Update About Page Content

### ISSUE THREAD

**Issue by jacksayshi** [oss-slu/rerum-playground#14]
We need to enhance our toolset by adding two new tools and update the content on the About page.

Tasks:
- Add New Tools:
Add two new tools, Adno and Universal Viewer, into the existing set of tools.
Reference information for the tools can be found in official websites:
[Adno](https://w.adno.app/#/)
[Universal Viewer](https://universalviewer.io/)

- Update About Page:
Add information about RERUM playground (what it does, why it is needed), JSON vs JSON LD and Manifests to the About section of the website.
Use the JSON vs. JSON-LD README for information of them.
For information about JSON Manifests (reference on what a manifest might look like), visit: [IIIF Cookbook](https://iiif.io/api/cookbook/).

**Comment by cubap** [comment]
https://github.com/IIIF/awesome-iiif is a great list to research for other low-hanging fruit. Viewers and annotation tools are the things to look at.
