### ISSUE TITLE
Fetch Manifest from URL

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#17]
**Description**: 
As a user,
I need the ability to fetch and load a manifest directly from a URL
So that I can easily load a valid JSON manifest for use.

Add functionality to allow users to fetch and load a manifest directly from a URL. This URL should point to a valid JSON manifest.

**Acceptance Criteria**:

- [x] - Users can input a URL pointing to a JSON manifest.
- [x] - The system validates the URL and 
    - [x] displays an appropriate message for success or failure.

**Comment by BeringeloF** [comment]
this functionality should go at the index.html or  tools.html ?
