### ISSUE TITLE
Implement Basic UI for Tool Selection

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#23]
**Description**: 
As a user,
I need to select a tool from a list of available tools
So that the selected tool loads and displays the manifest data.

Update UI tools component that allows users to select from a list of available tools. Once selected, the tool should be loaded with the manifest data.

**Acceptance Criteria**:

- [ ] Load the selected tool when a user makes a selection.
- [ ] Ensure the tool uses the selected manifest data.

**Comment by Sreeeja9866** [comment]
I will work on this
