### ISSUE TITLE
Consolidate CSS

### ISSUE THREAD

**Issue by alar12** [oss-slu/rerum-playground#27]
**Description**
As a developer,
I need to separate the CSS into corresponding external CSS files for each HTML page or module,
So that the project maintains consistent styling, modularity, and improves maintainability.

The project currently has CSS spread across HTML files and multiple external files. We need to organize the project by assigning each HTML file a corresponding CSS file for specific styles and creating a shared external CSS file for common styling rules.

Acceptance Criteria:

- [x] Consolidate inline and internal CSS from each HTML file into a corresponding external CSS file (e.g., tools.html should have tools.css).
- [x] Create a shared external CSS file (playground.css) for global or common styles used across multiple/all pages.
- [x] Ensure all pages reference their corresponding external CSS file or the shared playground.css as necessary.
- [x] Remove any redundant or duplicate CSS across files to streamline and optimize the CSS code.
- [x] Add appropriate comments in each CSS file to explain styling rules for readability and future maintenance.
- [x] Ensure that all styling and the codebase function as expected without any visual or layout issues.

**Comment by Virtual4087** [comment]
Can you assign this to me?

**Comment by iz-Manik** [comment]
Can you assign this to me? I am ready to work on this .

**Comment by alar12** [comment]
> Can you assign this to me?

You can work on it and raise the PR. If it fulfills all the requirements i will merge it.

**Comment by alar12** [comment]
> Can you assign this to me? I am ready to work on this .

You can work on it and raise the PR. If it fulfills all the requirements i will merge it.

**Comment by iz-Manik** [comment]
> > Can you assign this to me? I am ready to work on this .
> 
> You can work on it and raise the PR. If it fulfills all the requirements i will merge it.

Have proceeded with the tasks and raised a PR related to the same.

**Comment by Sreeeja9866** [comment]
I will work on this
